#服务配置
server:
  #端口
  port: 8081
  #服务编码
  tomcat:
    uri-encoding: UTF-8
#spring相关配置
spring:
  #应用配置
  application:
    #应用名称
    name: dubbo-web
  main:
    allow-bean-definition-overriding: true
  #nacos注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 120.55.169.247:8848

#dubbo消费端配置
dubbo:
  application:
    version: 1.0.0
    logger: slf4j
  cloud:
    #表示要订阅服务的服务名，可以配置'*'，代表订阅所有服务，不推荐使用。若需订阅多应用，使用 "," 分割。
    subscribed-services: dubbo-producer
    #调用多个服务: subscribed-services: dubbo-producer,xxxx, xxxx, xxxx,
  scan:
    #扫描路径
    base-packages: com.itheima.dubbo.web
  registry:
    address: spring-cloud://120.55.169.247
    #dubbo服务协议类型及端口，线程数【这里是默认配置】
    #register: false   # 只订阅
  protocol:
    name: dubbo
    port: 28081
    threads: 200
    accesslog: logs/dubbo-web-01.log
